---
ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b # frozen: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc
          - --branch=production

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: fc260393cc4ec09f8fc0a5ba4437f481c8b55dc1 # frozen: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: b05e028c5881819161d11cb543fd96a30c06cceb # frozen: v1.32.0
    hooks:
      - id: yamllint
        types: [yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 4de1378e4cd853bfc2b111b05fff35e2dbf809a3 # frozen: v0.9.0.6
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: ea8102762106cdca9c88829f1295b39a544706f3 # frozen: v1.6.26
    hooks:
      - id: actionlint
