---
name: "checkout-gerrit-change"
description: "Checkout a mirrored Gerrit change"

inputs:
  gerrit-refspec:
    description: "The Gerrit refspec for the change, eg: refs/changes/YY/NNYY/Z"
    required: true
  delay:
    description: "Delay in seconds to wait to make sure replication has finished. Default: 10s"
    required: false
    default: "10s"
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags. Default 1"
    required: false
    default: "1"
  repository:
    description: "Repository name with owner. For example actions/checkout"
    required: false
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. Otherwise, uses the default branch.
    required: false
    default: ${{ github.sha }}

runs:
  using: "composite"
  steps:
    - id: delay-checkout
      run: sleep ${{ inputs.delay }}
      shell: bash
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - id: gerrit-checkout
      run: git fetch origin ${{ inputs.gerrit-refspec }} && git checkout FETCH_HEAD
      shell: bash
